name: Build Binaries

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile:
    name: Build binaries for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: cfit_linux_x86_64
          - os: windows-latest
            asset_name: cfit_windows_x86_64.exe
          - os: macos-13
            asset_name: cfit_macos_x86_64
          - os: macos-latest
            asset_name: cfit_macos_arm64

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "v1.x"

      - name: Compile to binary
        run: deno compile --output=${{ matrix.asset_name }} --allow-all main.ts

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.asset_name }}
