name: Publish Binaries

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Publish binaries for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: cfit_linux_x86_64
          - os: windows-latest
            asset_name: cfit_windows_x86_64.exe
          - os: macos-13
            asset_name: cfit_macos_x86_64
          - os: macos-latest
            asset_name: cfit_macos_arm64

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "v1.x"

      - name: Compile to binary
        run: deno compile --output=${{ matrix.asset_name }} --allow-all main.ts

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.asset_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
